project:
  type: website
  output-dir: _site

website:
  title: "Billboard Top Ten Analysis (1958â€“2025)"
  navbar:
    left:
      - file: quarto.qmd
        text: Home
      - file: notebooks/analysis.ipynb
        text: Analysis
      - file: notebooks/scraper.ipynb
        text: Scraper
      - file: notebooks/spotify_api_test.ipynb
        text: Spotify API Test

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
